DELIVERIES_PER_COURIER_HOUR = 2.0
TIME_BUCKET_HOURS = 0.5
DELIVERIES_PER_COURIER_BUCKET = (
    DELIVERIES_PER_COURIER_HOUR * TIME_BUCKET_HOURS
)

OFFICIAL_TARGET_UTILIZATION = 1.0

WORKING_HOURS_BY_EMPLOYMENT_TYPE = {
    "FTE": 8,
    "FTC": 10,
}
BREAK_HOURS = 1

MONTHLY_COST_AED_BY_EMPLOYMENT_TYPE = {
    "FTE": 4000,
    "FTC": 4500,
}
WORKING_DAYS_PER_MONTH = 26
REVENUE_PER_DELIVERY_AED = 11.5

TRANSFER_LEAD_DAYS = (1, 3)
EXTERNAL_DRIVER_LEAD_DAYS = (2, 5)
